# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collage <- function(tiles, width, height, best_tiles, size) {
    .Call('_tipixel_collage', PACKAGE = 'tipixel', tiles, width, height, best_tiles, size)
}

base_mask <- function(distances, width, height, size, min_distance, max_distance) {
    .Call('_tipixel_base_mask', PACKAGE = 'tipixel', distances, width, height, size, min_distance, max_distance)
}

find_best_tiles <- function(img, size, base) {
    .Call('_tipixel_find_best_tiles', PACKAGE = 'tipixel', img, size, base)
}

add_grid_cpp <- function(img, size, grid_color) {
    .Call('_tipixel_add_grid_cpp', PACKAGE = 'tipixel', img, size, grid_color)
}

