# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collage <- function(tiles, width, height, best_tiles, tile_dim) {
    .Call('tipixel_collage', PACKAGE = 'tipixel', tiles, width, height, best_tiles, tile_dim)
}

#' @importFrom RcppParallel RcppParallelLibs
find_best_tiles <- function(img, width, height, base) {
    .Call('tipixel_find_best_tiles', PACKAGE = 'tipixel', img, width, height, base)
}

