# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decoupsynth_cpp <- function(img, lig, col) {
    .Call('tipixel_decoupsynth_cpp', PACKAGE = 'tipixel', img, lig, col)
}

