
#' transform data typically generated by readJPEG into something
#' magick can handle
#' @noRd
jpeg_to_bitmap <- function( jp ){
  dim <- dim(jp)
  width <- dim[2]
  height<- dim[1]
  out <- array( raw(4*width*height), dim = c(4, width, height) )
  out[4,,]   <- as.raw(255)
  out[1:3,,] <- as.raw( aperm(jp, c(3,2,1) ) * 255 )
  class(out) <- c("bitmap", "rgba")
  out
}
