
#' transform data typically generated by readJPEG into something
#' magick can handle
#' @noRd
jpeg_to_bitmap <- function( jp ){
  dim <- dim(jp)
  width <- dim[2]
  height<- dim[1]
  out <- array( raw(4*width*height), dim = c(4, width, height) )
  out[4,,]   <- as.raw(255)
  out[1:3,,] <- as.raw( aperm(jp, c(3,2,1) ) * 255 )
  class(out) <- c("bitmap", "rgba")
  out
}

#' Crops a square in the center of the image
#'
#' @param img an image, typically loaded with \code{\link[magick]{image_read}} or some
#' other function from \code{magick}
#' @return a square image
#' @importFrom magick image_info image_crop
#' @export
image_center_crop <- function(img){
  info <- image_info(img)
  width <- info$width
  height <- info$height

  geometry <- if( width > height){
    offset <- ( width - height ) / 2
    sprintf( "%dx%d+%d", height, height, offset)
  } else {
    offset <- (height - width )  / 2
    sprintf( "%dx%d+0+%d", width, width, offset)
  }
  image_crop(img, geometry = geometry)
}
